version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  laravel-storage:

services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: u156554963_ultimate
      MYSQL_USER: u156554963_ultimate
      MYSQL_PASSWORD: Julio2119??12
      MYSQL_ROOT_PASSWORD: AdminCredential
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Laravel Backend Service
  backend:
    build:
      context: ./Laravel
      dockerfile: Dockerfile
    container_name: laravel-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:80"
    volumes:
      - ./Laravel:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: u156554963_ultimate
      DB_USERNAME: u156554963_ultimate
      DB_PASSWORD: Julio2119??12
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000
    deploy:
      resources:
        limits:
          memory: 3g

  # Next.js Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./Next:/app
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - app-network

  # Browser container for accessing the web interfaces
  browser:
    image: jlesage/firefox:latest
    container_name: browser
    ports:
      - "5800:5800"
    environment:
      - VNC_PASSWORD=password
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
